# ===================================================================
# Spring Boot configuration for the "prod" profile.
#
# This configuration overrides the application.yml file.
# ===================================================================

# ===================================================================
# Standard Spring Boot properties.
# Full reference is available at:
# http://docs.spring.io/spring-boot/docs/current/reference/html/common-application-properties.html
# ===================================================================

logging:
  level:
    ROOT: INFO
    com.nexigroup.pagopa.cruscotto: INFO

spring:
  devtools:
    restart:
      enabled: false
    livereload:
      enabled: false
  jackson:
    serialization:
      indent-output: true
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    url: ${ENV_DATASOURCE_URL:jdbc:postgresql://localhost:3306/cruscotto}
    username: ${ENV_DATASOURCE_USERNAME:username}
    password: ${ENV_DATASOURCE_PASSWORD:password}
    hikari:
      poolName: Hikari
      auto-commit: false
  liquibase:
    enabled: false
  mail:
    host: localhost
    port: 25
    username:
    password:
  thymeleaf:
    cache: false
  quartz:
    properties:
      org.quartz.jobStore.driverDelegateClass: org.quartz.impl.jdbcjobstore.PostgreSQLDelegate
      org.quartz.jobStore.dataSource: cruscotto
      org.quartz.dataSource.cruscotto.provider: hikaricp
      org.quartz.dataSource.cruscotto.driver: org.postgresql.Driver
      org.quartz.dataSource.cruscotto.URL: ${ENV_DATASOURCE_URL:jdbc:postgresql://localhost:3306/cruscotto}
      org.quartz.dataSource.cruscotto.user: ${ENV_DATASOURCE_USERNAME:username}
      org.quartz.dataSource.cruscotto.password: ${ENV_DATASOURCE_PASSWORD:password}
      org.quartz.dataSource.cruscotto.validationQuery: select 1
      org.quartz.dataSource.cruscotto.maxConnections: 10
server:
  port: 8080

jhipster:
  cache:
    ehcache:
      time-to-live-seconds: 3600
      max-entries: 100
  security:
    authentication:
      jwt:
        base64-secret: ${ENV_JWT_KEY:key}
        token-validity-in-seconds: 86400
        token-validity-in-seconds-for-remember-me: 2592000
  mail:
    base-url: http://127.0.0.1:8080
  logging:
    use-json-format: false
    logstash:
      enabled: false
      host: localhost
      port: 5000
      ring-buffer-size: 512

application:
  enable-csrf: false
  password:
    day-password-expired: 60
    failed-login-attempts: 4
    hours-key-reset-password-expired: 1
  pago-pa-client:
    proxy-host:
    proxy-port:
    taxonomy:
      url: ${ENV_TAXONOMY_URL:http://localhost:8080/taxonomy}
    maintenance:
      url: ${ENV_STATION_MAINTENANCES_URL:http://localhost:8080/station-maintenances}
      api-key-name: ${ENV_STATION_MAINTENANCES_API_KEY_NAME:api-key-name}
      api-key-value: ${ENV_STATION_MAINTENANCES_API_KEY_VALUE:api-key-value}
  job:
    load-taxonomy-job:
      enabled: true
      cron: 0 0/30 07-8 ? * MON,TUE,WED,THU,FRI *
    load-maintenance-job:
      enabled: true
      cron: 0 0/30 07-8 ? * MON,TUE,WED,THU,FRI *
  liquibase:
    async-start: false
