# ===================================================================
# Spring Boot configuration for the "prod" profile.
#
# This configuration overrides the application.yml file.
# ===================================================================

# ===================================================================
# Standard Spring Boot properties.
# Full reference is available at:
# http://docs.spring.io/spring-boot/docs/current/reference/html/common-application-properties.html
# ===================================================================

logging:
  level:
    ROOT: INFO
    com.nexigroup.pagopa.cruscotto: INFO

spring:
  cloud:
    aws:
      credentials:
        access-key: ${AWS_ACCESS_KEY}
        secret-key: ${AWS_SECRET_KEY}
      region:
        static: ${AWS_REGION}
  jackson:
    serialization:
      indent-output: true
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    url: ${ENV_DATASOURCE_URL:jdbc:postgresql://localhost:3306/cruscotto}
    username: ${ENV_DATASOURCE_USERNAME:username}
    password: ${ENV_DATASOURCE_PASSWORD:password}
    hikari:
      poolName: Hikari
      auto-commit: false
  liquibase:
    enabled: false
  thymeleaf:
    cache: false
  quartz:
    properties:
      org.quartz.jobStore.driverDelegateClass: org.quartz.impl.jdbcjobstore.PostgreSQLDelegate
      org.quartz.jobStore.dataSource: cruscotto
      org.quartz.dataSource.cruscotto.provider: hikaricp
      org.quartz.dataSource.cruscotto.driver: org.postgresql.Driver
      org.quartz.dataSource.cruscotto.URL: ${ENV_DATASOURCE_URL:jdbc:postgresql://localhost:3306/cruscotto}
      org.quartz.dataSource.cruscotto.user: ${ENV_DATASOURCE_USERNAME:username}
      org.quartz.dataSource.cruscotto.password: ${ENV_DATASOURCE_PASSWORD:password}
      org.quartz.dataSource.cruscotto.validationQuery: select 1
      org.quartz.dataSource.cruscotto.maxConnections: 10
server:
  port: 8080

jhipster:
  cache:
    ehcache:
      time-to-live-seconds: 3600
      max-entries: 100
  security:
    authentication:
      jwt:
        base64-secret: ${ENV_JWT_KEY:key}
        token-validity-in-seconds: 86400
        token-validity-in-seconds-for-remember-me: 2592000
  logging:
    use-json-format: false
    logstash:
      enabled: false
      host: localhost
      port: 5000
      ring-buffer-size: 512

application:
  mail:
    base-url: ${SITE_BASE_URL}
  aws:
    ses:
      user: ${AWS_SES_USER}
  enable-csrf: false
  password:
    day-password-expired: 60
    failed-login-attempts: 4
    hours-key-reset-password-expired: 1
  pago-pa-client:
    proxy-host:
    proxy-port:
    taxonomy:
      url: ${ENV_TAXONOMY_URL:http://localhost:8080/taxonomy/v1}
    back-office:
      url: ${ENV_BACK_OFFICE_URL:http://localhost:8080/back-office/v1}
      api-key-name: ${ENV_BACK_OFFICE_API_KEY_NAME:api-key-name}
      api-key-value: ${ENV_BACK_OFFICE_API_KEY_VALUE:api-key-value}
    cache:
      url: ${ENV_CACHE_URL:http://localhost:8080/back-office/v1}
      api-key-name: ${ENV_CACHE_API_KEY_NAME:api-key-name}
      api-key-value: ${ENV_CACHE_API_KEY_VALUE:api-key-value}
    stand-in:
      url: ${ENV_STAND_IN_URL:http://localhost:8080/technical-support/stand-in/api/v1}
      api-key-name: ${ENV_STAND_IN_API_KEY_NAME:api-key-name}
      api-key-value: ${ENV_STAND_IN_API_KEY_VALUE:api-key-value}
  auth-group:
    super-admin: NEXI
  job:
    load-taxonomy-job:
      enabled: true
      cron: 0 0/30 07-8 ? * MON,TUE,WED,THU,FRI *
    load-maintenance-job:
      enabled: true
      cron: 0 0/30 07-8 ? * MON,TUE,WED,THU,FRI *
    load-registry-job:
      enabled: true
      cron: 0 0/30 07-8 ? * MON,TUE,WED,THU,FRI *
    kpi-a1-job:
      enabled: true
      cron: 0 0/5 08-23 ? * MON,TUE,WED,THU,FRI,SAT,SUN *
      limit: 20
    kpi-a2-job:
      enabled: true
      cron: 0 0/5 08-23 ? * MON,TUE,WED,THU,FRI,SAT,SUN *
      limit: 20
    kpi-b2-job:
      enabled: true
      cron: 0 0/5 08-23 ? * MON,TUE,WED,THU,FRI,SAT,SUN *
      limit: 20
    kpi-b9-job:
      enabled: true
      cron: 0 0/5 08-23 ? * MON,TUE,WED,THU,FRI,SAT,SUN *
      limit: 20
    kpi-b3-job:
      enabled: true
      cron: 0 0/5 08-23 ? * MON,TUE,WED,THU,FRI,SAT,SUN *
      limit: 20
    kpi-b1-job:
      enabled: true
      cron: 0 0/2 08-23 ? * MON,TUE,WED,THU,FRI,SAT,SUN *
      limit: 20
    kpi-b4-job:
      enabled: true
      cron: 0 0/5 08-23 ? * MON,TUE,WED,THU,FRI,SAT,SUN *
      limit: 20
    load-stand-in-data-job:
      enabled: true
      cron-expression: 0 0 0 * * ? # Every day at midnight
    clear-log-job:
      cron: 0 0/20 05-6 ? * MON,TUE,WED,THU,FRI,SAT,SUN *
      days: 7

  liquibase:
    async-start: false
    dbVersion: 1.1.7

decorator:
  datasource:
    p6spy:
      enable-logging: false
