package com.nexigroup.pagopa.cruscotto.domain.enumeration;

public enum TaxonomyField {
    INSTITUTION_TYPE_CODE("CODICE TIPO ENTE CREDITORE"),
    INSTITUTION_TYPE("TIPO ENTE CREDITORE"),
    AREA_PROGRESSIVE_CODE("PROGRESSIVO MACRO AREA PER ENTE CREDITORE"),
    AREA_NAME("NOME MACRO AREA"),
    AREA_DESCRIPTION("DESCRIZIONE MACRO AREA"),
    SERVICE_TYPE_CODE("CODICE TIPOLOGIA SERVIZIO"),
    SERVICE_TYPE("TIPO SERVIZIO"),
    SERVICE_TYPE_DESCRIPTION("DESCRIZIONE TIPO SERVIZIO"),
    VERSION("VERSIONE TASSONOMIA"),
    REASON_COLLECTION("MOTIVO GIURIDICO DELLA RISCOSSIONE"),
    TAKINGS_IDENTIFIER("DATI SPECIFICI INCASSO"),
    VALIDITY_START_DATE("DATA INIZIO VALIDITA"),
    VALIDITY_END_DATE("DATA FINE VALIDITA");

    public final String field;

    TaxonomyField(String field) {
        this.field = field;
    }
}
